spring.application.name=ecommerce-marketplace

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_marketplace
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.jpa.open-in-view=false